services:
    kernel.listener.bigfoot_user_menu_listener:
        class: Bigfoot\Bundle\UserBundle\Listener\MenuListener
        tags:
            - { name: kernel.event_listener, event: bigfoot.menu.generate, method: onMenuGenerate }
    kernel.listener.bigfoot_user_kernel_listener:
        class: Bigfoot\Bundle\UserBundle\Listener\KernelListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
    form.type.role_menu:
        class: Bigfoot\Bundle\UserBundle\Form\BigfootRoleMenuType
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: bigfootrolemenutype }

    # User Manager
    bigfoot_user.manager.user:
        class: Bigfoot\Bundle\UserBundle\Manager\UserManager
        arguments: [ @doctrine.orm.entity_manager, @security.encoder_factory, @security.user_checker, @security.context, @session, @bigfoot_user.mailer.user, @bigfoot_core.generator.token_generator ]
    # User Mailer
    bigfoot_user.mailer.user:
        class: Bigfoot\Bundle\UserBundle\Mailer\UserMailer
        parent: bigfoot_core.mailer.abstract
    # User Listener
    bigfoot_user.listener.user:
        class: Bigfoot\Bundle\UserBundle\Listener\UserListener
        arguments: [ @bigfoot_user.manager.user ]
    # User Type
    bigfoot_user.form.type.user:
        class: Bigfoot\Bundle\UserBundle\Form\Type\BigfootUserType
        tags:
            - { name: form.type, alias: bigfoot_user }
    # ForgotPassword Type
    bigfoot_user.form.type.forgot_password:
        class: Bigfoot\Bundle\UserBundle\Form\Type\ForgotPasswordType
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: admin_forgot_password }