services:
    kernel.listener.bigfoot_user_kernel_listener:
        class: Bigfoot\Bundle\UserBundle\Listener\KernelListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
    form.type.role_menu:
        class: Bigfoot\Bundle\UserBundle\Form\BigfootRoleMenuType
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: bigfootrolemenutype }

    # Menu Subscriber
    bigfoot_user.subscriber.menu:
        class: Bigfoot\Bundle\UserBundle\Subscriber\MenuSubscriber
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_subscriber }

    # User Manager
    bigfoot_user.manager.user:
        class: Bigfoot\Bundle\UserBundle\Manager\UserManager
        arguments:
            - @doctrine.orm.entity_manager
            - @security.encoder_factory
            - @security.user_checker
            - @security.context
            - @session
            - @bigfoot_user.mailer.user
            - @bigfoot_core.generator.token

    # User Mailer
    bigfoot_user.mailer.user:
        class: Bigfoot\Bundle\UserBundle\Mailer\UserMailer
        parent: bigfoot_core.mailer.abstract

    # User Listener
    bigfoot_user.listener.user:
        class: Bigfoot\Bundle\UserBundle\Listener\UserListener
        arguments:
            - @bigfoot_user.manager.user
        tags:
            - { name: kernel.event_subscriber }

    # User Type
    bigfoot_user.form.type.user:
        class: Bigfoot\Bundle\UserBundle\Form\Type\UserType
        arguments:
            - @security.context
            - %bigfoot_core.languages.front%
        tags:
            - { name: form.type, alias: admin_user }

    # ForgotPassword Type
    bigfoot_user.form.type.forgot_password:
        class: Bigfoot\Bundle\UserBundle\Form\Type\ForgotPasswordType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: admin_forgot_password }

    # ResetPassword Type
    bigfoot_user.form.type.reset_password:
        class: Bigfoot\Bundle\UserBundle\Form\Type\ResetPasswordType
        tags:
            - { name: form.type, alias: admin_reset_password }

    # Role Type
    bigfoot_user.form.type.role:
        class: Bigfoot\Bundle\UserBundle\Form\Type\RoleType
        tags:
            - { name: form.type, alias: admin_role }